const express = require('express');
const { getRecentEvents } = require('../controllers/eventController');
const { requireAuth } = require('../middleware/authMiddleware');
const validateRequest = require('../middleware/validateRequest');
const { eventsQuerySchema } = require('../utils/validators');

const router = express.Router();

/**
 * @openapi
 * tags:
 *   name: Events
 *   description: Real-time safety events generated by wearable devices
 */

/**
 * @openapi
 * /api/events:
 *   get:
 *     tags: [Events]
 *     summary: List recent safety events
 *     description: |
 *       Returns safety events sorted newest first, one page at a time.
 *       Defaults to page 1 with 20 events. Does not load the full collection.
 *       Worker and device fields are populated.
 *       Use the page, limit, severity, eventType, and workerId parameters to filter results.
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: page
 *         schema:
 *           type: integer
 *           minimum: 1
 *           default: 1
 *         description: Page number (1-based). Page 1 is the 20 most recent events.
 *         example: 1
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *           minimum: 1
 *           maximum: 100
 *           default: 20
 *         description: Events per page (default 20)
 *         example: 20
 *       - in: query
 *         name: severity
 *         schema:
 *           type: string
 *           enum: [WARNING, HIGH, CRITICAL]
 *         description: Filter events by severity level
 *         example: CRITICAL
 *       - in: query
 *         name: eventType
 *         schema:
 *           type: string
 *           enum: [HIGH_TEMPERATURE, LOW_BATTERY, FALL_DETECTED, NO_MOVEMENT, GEOFENCE_BREACH, SOS]
 *         description: Filter events by type
 *         example: FALL_DETECTED
 *       - in: query
 *         name: workerId
 *         schema:
 *           $ref: '#/components/schemas/ObjectId'
 *         description: Filter events for a specific worker (MongoDB ObjectId)
 *         example: 6650f2a1c2e4b12345abcd01
 *     responses:
 *       200:
 *         description: Event list retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 count:
 *                   type: integer
 *                   example: 20
 *                 page:
 *                   type: integer
 *                   example: 1
 *                 limit:
 *                   type: integer
 *                   example: 20
 *                 total:
 *                   type: integer
 *                   example: 3500
 *                 totalPages:
 *                   type: integer
 *                   example: 175
 *                 data:
 *                   type: array
 *                   items:
 *                     $ref: '#/components/schemas/Event'
 *       401:
 *         description: Missing or invalid Bearer token
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ErrorResponse'
 */
router.get('/', requireAuth, validateRequest(eventsQuerySchema), getRecentEvents);

module.exports = router;
