const EVENT_TYPES = [
  'HIGH_TEMPERATURE',
  'LOW_BATTERY',
  'FALL_DETECTED',
  'NO_MOVEMENT',
  'GEOFENCE_BREACH',
  'SOS',
];

const EVENT_SEVERITY_MAP = {
  HIGH_TEMPERATURE: 'WARNING',
  LOW_BATTERY: 'WARNING',
  FALL_DETECTED: 'CRITICAL',
  NO_MOVEMENT: 'HIGH',
  GEOFENCE_BREACH: 'HIGH',
  SOS: 'CRITICAL',
};

const INCIDENT_CREATING_SEVERITIES = ['HIGH', 'CRITICAL'];

module.exports = {
  EVENT_TYPES,
  EVENT_SEVERITY_MAP,
  INCIDENT_CREATING_SEVERITIES,
};
